export default class PageRoutes {
  static readonly INDEX: string = 'pages/Index';
  static readonly HOME: string = 'pages/Home';
  static readonly GAME: string = 'pages/Game';
  static readonly RESULT: string = 'pages/Result';
  static readonly STATS: string = 'pages/Stats';
  static readonly HISTORY: string = 'pages/History';
  static readonly LOGS: string = 'pages/Logs';
  static readonly SETTINGS: string = 'pages/Settings';
}
